function [] = createNcVariable(filename, name, data, dimensions, varargin)
nccreate( ...
    filename, ...
    name, ...
    'Dimensions', dimensions, ...
    'Datatype', class(data), ...
    'Format', 'netcdf4' ...
);
ncwrite(filename, name, data);

for ii = 1:2:length(varargin)
    key = varargin{ii};
    value = varargin{ii+1};
    ncwriteatt(filename, name, key, value);
end

