function [] = createNcDimension(filename, name, data, varargin)

assert(isvector(data), "dimension data should be a one-dimensional column vector.") 
nccreate( ...
    filename, ...
    name, ...
    'Dimensions', {name, length(data)}, ...
    'Datatype', class(data), ...
    'Format', 'netcdf4' ...
);
ncwrite(filename, name, data);

for ii = 1:2:length(varargin)
    key = varargin{ii};
    value = varargin{ii+1};
    ncwriteatt(filename, name, key, value);
end
